version: 1.0.{build}

image: Visual Studio 2022

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

before_build:
  - nuget restore

build:
  project: NovaHack.sln
  parallel: true
  verbosity: minimal

artifacts:
  - path: '**\*.exe'
    name: Executable
